### PR TITLE
Update build-artik.inc

### PR DESCRIPTION
**Pull request by koansoftware**
Solve git clone failure

### CODE REVIEW

**Comment by agherzan** [comment]
Could you please detail the issue with logs, how was fixed and why?

**Comment by koansoftware** [comment]
Hi Andrei,
the problem is very simple.
If you try the following command you can see that it fails the download
`git clone git://git@github.com/resin-os/build-artik.git
`

**Comment by koansoftware** [comment]
$ bitbake -c cleansstate u-boot-artik710
Loading cache: 100% |##########################################################################################################| Time: 0:00:00
Loaded 2051 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal-4.8"
TARGET_SYS        = "aarch64-poky-linux"
MACHINE           = "artik710"
DISTRO            = "poky"
DISTRO_VERSION    = "2.2.2"
TUNE_FEATURES     = "aarch64"
TARGET_FPU        = ""
meta
meta-poky
meta-yocto-bsp    = "morty:4b1974d57c997840f7134244145b51c6790c795a"
meta-oe           = "morty:b40116cf457b88a2db14b86fda9627fb34d56ae6"
meta-artik        = "morty:bf9e2cdaa1e034ff0afa626d105f9f7c16c083f8"
meta-artik710     = "morty:903a29b0b0e38371790edf62b4d6b6dc788d6672"
...
Cloning into bare repository '/home/koan/yocto-artik710-morty/poky/build/downloads/git2/github.com.resin-os.uboot-artik7.git'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR: u-boot-artik710-1.0-r0 do_fetch: Fetcher failure for URL: 'git://git@github.com/resin-os/uboot-artik7.git;protocol=ssh'. Unable to fetch URL from any source.
ERROR: u-boot-artik710-1.0-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/koan/yocto-artik710-morty/poky/build/tmp/work/artik710-poky-linux/u-boot-artik710/1.0-r0/temp/log.do_fetch.12315
ERROR: Task (/home/koan/yocto-artik710-morty/poky/meta-artik710/recipes-bsp/u-boot/u-boot-artik710.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 589 tasks of which 588 didn't need to be rerun and 1 failed.

**Comment by agherzan** [comment]
@koansoftware sure but how did this work in the past? Did current change in poky affected this?

**Comment by koansoftware** [comment]
Andrei, it looks likely a problem related to github rather than Poky IMHO

**Comment by agherzan** [comment]
@floion do you know what happened here?

**Comment by floion** [comment]
What do you mean?

**Comment by agherzan** [comment]
@floion I was curious what was the issue here and how was it working before? Because we were using this layer for a while now.

**Comment by floion** [comment]
I did not investigate what was happened. I confirm I got the same issue trying to clone and since we switched all the other repos on https, I thought we do the same with this one also.

**Pull request merged**
